package suite

import (
	"time"

	"github.com/google/uuid"
)

type Kind string

const (
	KindManual Kind = "manual"
	KindAuto   Kind = "auto"
	KindMixed  Kind = "mixed"
)

type ItemSource string

const (
	ItemManualAdded   ItemSource = "manual_added"
	ItemAutoGenerated ItemSource = "auto_generated"
	ItemAutoSelected  ItemSource = "auto_selected"
)

type Suite struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"projectId"`
	ServiceID   uuid.UUID `json:"serviceId"`
	Name        string    `json:"name"`
	Kind        Kind      `json:"kind"`
	Description string    `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Item struct {
	ID         uuid.UUID  `json:"id"`
	SuiteID    uuid.UUID  `json:"suiteId"`
	TestCaseID uuid.UUID  `json:"testCaseId"`
	ItemOrder  int        `json:"itemOrder"`
	Source     ItemSource `json:"source"`
	Enabled    bool       `json:"enabled"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

type CreateSuiteInput struct {
	ProjectID   uuid.UUID `json:"projectId"`
	ServiceID   uuid.UUID `json:"serviceId"`
	Name        string    `json:"name"`
	Kind        Kind      `json:"kind"`
	Description string    `json:"description"`
}

type AddItemInput struct {
	TestCaseID uuid.UUID  `json:"testCaseId"`
	ItemOrder  int        `json:"itemOrder"`
	Source     ItemSource `json:"source"`
	Enabled    *bool      `json:"enabled"`
}

type ListFilter struct {
	ProjectID uuid.UUID
	ServiceID uuid.UUID
}
